# SPDX-License-Identifier: Apache-2.0

from building import *
import os
import subprocess

cwd = GetCurrentDir()
root = os.path.abspath(os.path.join(cwd, '..', '..', '..'))
aic_root = os.path.abspath(os.path.join(cwd, 'third_party', 'lvgl-aic'))
build_dir = os.path.join(root, 'build')


def _git(path, args):
    try:
        output = subprocess.Popen(['git', '-C', path] + args,
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE).communicate()[0]
    except Exception:
        return ''
    if not output:
        return ''
    return output.decode('utf-8', 'replace').strip().splitlines()[0]


def _dirty(path):
    # The board build script temporarily rewrites a tracked lvgl-aic profile
    # defconfig while feature switches are active; that transient edit is not
    # source drift and must not mark a clean commit as dirty.
    try:
        output = subprocess.Popen(['git', '-C', path, 'status', '--porcelain',
                                   '--untracked-files=no'],
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE).communicate()[0]
    except Exception:
        return '+dirty'
    if not output:
        return ''
    # Do not strip the whole output: porcelain prefixes each line with two
    # status columns, and stripping would eat the first line's leading space.
    for line in output.decode('utf-8', 'replace').splitlines():
        changed = line[3:].replace('\\', '/')
        if changed.startswith('target/configs/') and '_lvgl-aic-' in changed:
            continue
        return '+dirty'
    return ''


def _identity(path, tag_first=False):
    commit = _git(path, ['rev-parse', '--short=8', 'HEAD'])
    if not commit:
        return 'unknown'
    dirty = _dirty(path)
    name = ''
    if tag_first:
        name = _git(path, ['describe', '--tags', '--always'])
        if name:
            name = name.lstrip('v')
    if not name:
        name = _git(path, ['rev-parse', '--abbrev-ref', 'HEAD'])
        if not name or name == 'HEAD':
            name = '(detached)'
        elif len(name) > 28:
            name = name[:27] + '+'
    return '%s@%s%s' % (name, commit, dirty)


lvgl_root = os.path.join(cwd, 'third_party', 'lvgl')
# One identity per line: the ulog line buffer is 128 bytes including the
# timestamp, level/tag and colour codes, so a combined banner loses its tail
# on the board console. _identity() bounds each name, keeping every line well
# inside that budget even with a dirty tree.
build_identities = (
    ('AIC_LVGL_BUILD_SDK', 'sdk=%s' % _identity(root)),
    ('AIC_LVGL_BUILD_AIC', 'lvgl-aic=%s' % _identity(aic_root)),
    ('AIC_LVGL_BUILD_LVGL', 'lvgl=%s' % _identity(lvgl_root, tag_first=True)),
)

if not os.path.isdir(build_dir):
    os.makedirs(build_dir)
with open(os.path.join(build_dir, 'lvgl_aic_build_id.h'), 'w') as header:
    header.write('/* Generated by application/rt-thread/lvgl-aic-smoke/SConscript. */\n')
    header.write('#ifndef AIC_LVGL_BUILD_ID_H\n')
    header.write('#define AIC_LVGL_BUILD_ID_H\n')
    for macro, identity in build_identities:
        header.write('#define %s "%s"\n' % (macro, identity))
    header.write('#endif\n')

group = SConscript('third_party/lvgl-aic/SConscript')
group += DefineGroup(
    'LVGL-AIC-SMOKE',
    Glob('*.c'),
    depend=['AIC_LVGL_SMOKE_APP'],
    CPPPATH=[
        cwd,
        build_dir,
        aic_root,
        os.path.join(aic_root, 'include'),
        os.path.join(aic_root, 'port'),
        os.path.join(aic_root, 'tests', 'manual'),
        os.path.join(cwd, 'ota'),
        os.path.join(cwd, 'watchdog'),
    ],
)

# Bench recovery watchdog (watchdog/): resets a locked-up board during tests. A
# bench tool of this app, not an LVGL feature; the product supervises itself.
if GetDepend('AIC_LVGL_SMOKE_WATCHDOG'):
    group += DefineGroup('LVGL-AIC-SMOKE-WATCHDOG', [File('watchdog/lv_aic_watchdog.c')],
                         depend=['AIC_LVGL_SMOKE_WATCHDOG'],
                         CPPPATH=[os.path.join(cwd, 'watchdog')])

# CAN-USB OTA debug endpoint (ota/, third_party/iso14229). A bench tool of this
# app, not an LVGL feature: it reuses forklift-meter-platform's UDS/update
# code and links the SDK native OTA installer. See docs/ota-can-reuse.md.
if GetDepend('AIC_LVGL_SMOKE_CAN_OTA'):
    ota_root = os.path.join(cwd, 'ota')
    ota_iso = os.path.join(cwd, 'third_party', 'iso14229', 'src')
    ota_pkg = os.path.join(root, 'packages', 'artinchip', 'ota')
    ota_crypto = os.path.join(root, 'packages', 'third-party', 'mbedtls', 'mbedtls')
    prj_chip = GetDepend('PRJ_CHIP').strip('"')
    ota_src = ['ota/update/lv_aic_can_ota.c', 'ota/update/lv_aic_can_ota_widget.c',
               'ota/update/meter_update.c', 'ota/update/meter_package.c',
               'ota/update/meter_update_backend_aic.c', 'ota/update/meter_sha256_aic.c',
               'ota/protocols/uds/meter_uds.c',
               'third_party/iso14229/src/server.c', 'third_party/iso14229/src/tp.c',
               'third_party/iso14229/src/util.c', 'third_party/iso14229/src/log.c',
               'third_party/iso14229/src/tp/isotp_c.c',
               'third_party/iso14229/src/tp/isotp-c/isotp.c']
    ota_native = os.path.join(build_dir, 'lvgl-ota-native')
    Env.VariantDir(ota_native, ota_pkg, duplicate=0)
    ota_src += [os.path.join(ota_native, name) for name in ('ota.c', 'burn.c')]
    # ota/ resolves update/, protocols/, contracts/ and tp/ (iso14229's
    # isotp_c.c includes tp/isotp_c_shim.h); cwd resolves the shim's
    # third_party/iso14229/... include.
    ota_paths = [ota_root, cwd, ota_iso, ota_pkg,
                 os.path.join(ota_crypto, 'include'), os.path.join(ota_crypto, 'library'),
                 os.path.join(root, 'packages', 'artinchip', 'env'),
                 os.path.join(root, 'packages', 'third-party', 'fdtlib'),
                 os.path.join(root, 'bsp', 'common', 'include'),
                 os.path.join(root, 'bsp', 'artinchip', 'sys', prj_chip, 'include')]
    group += DefineGroup('LVGL-AIC-SMOKE-CAN-OTA',
                         [File(path) for path in ota_src],
                         depend=['AIC_LVGL_SMOKE_CAN_OTA'], CPPPATH=ota_paths,
                         CPPDEFINES=['UDS_SYS=0', 'UDS_CUSTOM_MILLIS', 'UDS_TP_ISOTP_C',
                                     'AIC_LVGL_BSP_RTTHREAD=1',
                                     'AIC_LVGL_BSP_MPP=1', 'UDS_LOG_LEVEL=0',
                                     'UDS_SERVER_DEFAULT_P2_MS=1',
                                     'UDS_SERVER_RECV_BUF_SIZE=1024',
                                     'UDS_SERVER_SEND_BUF_SIZE=1024',
                                     'ISO_TP_DEFAULT_ST_MIN_US=0',
                                     'ISO_TP_DEFAULT_RESPONSE_TIMEOUT_US=1000000',
                                     'METER_AIC_OTA',
                                     # The progress overlay uses the built-in
                                     # 14 px font; global so LVGL compiles it.
                                     'LV_FONT_MONTSERRAT_14=1'])
    for api in ('start', 'stop', 'started', 'stopped', 'view'):
        Env.AppendUnique(LINKFLAGS=['-Wl,-u,lv_aic_can_ota_' + api])
    for api in ('create', 'destroy', 'present_view', 'refresh', 'ui_poll', 'ui_request'):
        Env.AppendUnique(LINKFLAGS=['-Wl,-u,lv_aic_can_ota_widget_' + api])
    for api in ('meter_uds_init', 'UDSServerPoll', 'meter_update_init',
                'meter_package_init', 'meter_aic_update_backend'):
        Env.AppendUnique(LINKFLAGS=['-Wl,-u,' + api])

Return('group')
