# SPDX-License-Identifier: Apache-2.0

from building import *
import os
import subprocess

cwd = GetCurrentDir()
root = os.path.abspath(os.path.join(cwd, '..', '..', '..'))
aic_root = os.path.abspath(os.path.join(cwd, 'third_party', 'lvgl-aic'))
build_dir = os.path.join(root, 'build')


def _git(path, args):
    try:
        output = subprocess.Popen(['git', '-C', path] + args,
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE).communicate()[0]
    except Exception:
        return ''
    if not output:
        return ''
    return output.decode('utf-8', 'replace').strip().splitlines()[0]


def _dirty(path):
    # The board build script temporarily rewrites a tracked lvgl-aic profile
    # defconfig while feature switches are active; that transient edit is not
    # source drift and must not mark a clean commit as dirty.
    try:
        output = subprocess.Popen(['git', '-C', path, 'status', '--porcelain',
                                   '--untracked-files=no'],
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE).communicate()[0]
    except Exception:
        return '+dirty'
    if not output:
        return ''
    # Do not strip the whole output: porcelain prefixes each line with two
    # status columns, and stripping would eat the first line's leading space.
    for line in output.decode('utf-8', 'replace').splitlines():
        changed = line[3:].replace('\\', '/')
        if changed.startswith('target/configs/') and '_lvgl-aic-' in changed:
            continue
        return '+dirty'
    return ''


def _identity(path, tag_first=False):
    commit = _git(path, ['rev-parse', '--short=8', 'HEAD'])
    if not commit:
        return 'unknown'
    dirty = _dirty(path)
    name = ''
    if tag_first:
        name = _git(path, ['describe', '--tags', '--always'])
        if name:
            name = name.lstrip('v')
    if not name:
        name = _git(path, ['rev-parse', '--abbrev-ref', 'HEAD'])
        if not name or name == 'HEAD':
            name = '(detached)'
        elif len(name) > 28:
            name = name[:27] + '+'
    return '%s@%s%s' % (name, commit, dirty)


lvgl_root = os.path.join(cwd, 'third_party', 'lvgl')
# One identity per line: the ulog line buffer is 128 bytes including the
# timestamp, level/tag and colour codes, so a combined banner loses its tail
# on the board console. _identity() bounds each name, keeping every line well
# inside that budget even with a dirty tree.
build_identities = (
    ('AIC_LVGL_BUILD_SDK', 'sdk=%s' % _identity(root)),
    ('AIC_LVGL_BUILD_AIC', 'lvgl-aic=%s' % _identity(aic_root)),
    ('AIC_LVGL_BUILD_LVGL', 'lvgl=%s' % _identity(lvgl_root, tag_first=True)),
)

if not os.path.isdir(build_dir):
    os.makedirs(build_dir)
with open(os.path.join(build_dir, 'lvgl_aic_build_id.h'), 'w') as header:
    header.write('/* Generated by application/rt-thread/lvgl-aic-smoke/SConscript. */\n')
    header.write('#ifndef AIC_LVGL_BUILD_ID_H\n')
    header.write('#define AIC_LVGL_BUILD_ID_H\n')
    for macro, identity in build_identities:
        header.write('#define %s "%s"\n' % (macro, identity))
    header.write('#endif\n')

group = SConscript('third_party/lvgl-aic/SConscript')
group += DefineGroup(
    'LVGL-AIC-SMOKE',
    Glob('*.c'),
    depend=['AIC_LVGL_SMOKE_APP'],
    CPPPATH=[
        cwd,
        build_dir,
        os.path.join(aic_root, 'include'),
        os.path.join(aic_root, 'port'),
        os.path.join(aic_root, 'tests', 'manual'),
    ],
)

Return('group')
